### ISSUE TITLE
IDE: Symlinking Executable Breaks UI Image Loading 

### ISSUE THREAD

**Issue by distransient** [ivansafrin/Polycode#511]
Steps to reproduce:
1. Build the IDE as usual
2. Create a symlink to the IDE executable
3. Run the IDE via the symlink

For example, running the following commands

``` bash
git clone git://github.com/ivansafrin/Polycode
cd Polycode
./BuildLinux.sh
cd IDE/Build/Linux
make
cd ../../../..
ln -s Polycode/IDE/Build/Linux/Build/Polycode Polycode
./Polycode
```

Results in the following output:

```
DIR: /home/michael
Reading xml from /home/michael/.polycode/config.xml
Reading xml from SyntaxThemes/default.xml
LOADING THEME: dark
Reading xml from UIThemes/dark/theme.xml
Opening project  /home/michael/code/src/Frontier/Frontier.polyproject
CREATING PROJECT Frontier /home/michael/code/src/Frontier
Reading xml from /home/michael/code/src/Frontier/Frontier.polyproject
Reading xml from default/default.sprite
Reading xml from /home/michael/code/src/Frontier/Resources/scene.entity
ading xml file: Failed to open file
Error adding archive to resource manager... File not found
Loading config: UIThemes/dark/theme.xml
Error loading config file...
Error: Failed to open file
Error adding archive to resource manager... File not found
```

Followed by a flurry of `Error opening png file ("main/foo.png")`, `Error loading main/foo.png`, `Error loading image ("main/foo.png"), using default texture.` and `empty texture filename, using default texture.` errors, as well as the IDE looking as follows:

![Broken IDE UI](https://cloud.githubusercontent.com/assets/2965148/3647933/31173b54-1104-11e4-8752-44e8aec0ddca.png)

**Comment by topokel** [comment]
Closing old inactionable issues.
