### ISSUE TITLE
Tutorials and Documentation are outdated

### ISSUE THREAD

**Issue by suchipi** [ivansafrin/Polycode#514]
All the content under http://polycode.org/learn/ (Namely, the [Tutorials](http://polycode.org/wiki/index.php?n=Main.Tutorials), [C++ Documentation](http://polycode.org/docs/polycore/), and [Lua Documentation](http://polycode.org/docs/lua/)) is outdated due to the screenrewrite (which occurred ~9 months ago).

**Comment by ivansafrin** [comment]
Well, the new site has update docs, if incomplete, so im going to close this.
