### ISSUE TITLE
Typing in a textbox : each new letter replaces what was written before

### ISSUE THREAD

**Issue by charnet3d** [ivansafrin/Polycode#549]
When trying to replace the default project name "Untitled" with some other text, I select it and start typing, but each new letter replaces what was written before. Here's a gif showing the problem:

![text_selection](https://cloud.githubusercontent.com/assets/2863796/3894077/d0bd2dc4-2240-11e4-912b-d50ee1551731.gif)

I think this must be some issue with the selection that persists even after typing something in the textbox.

I also experienced the other selection problem described by this issue: https://github.com/ivansafrin/Polycode/issues/537

**Comment by fodinabor** [comment]
Fixed by #587
