### ISSUE TITLE
.sprites needs a save function

### ISSUE THREAD

**Issue by ghost** [ivansafrin/Polycode#593]
hello,

ive been working, again on a tutorial. but have ran into quite an annoying bug.

on making a .sprite, i make all the directions, do all the naming, sizes blah blah blah. but on running and saving the project. i exit and then open polycode, open the project, and all my .sprite setting are completely gone. so have to do it again.
i see on the .sprites menubar, that a symbol [*] does not show to say that this has not been saved, that edits have been made.
i think it would be good to have just so things have been saved.

[idea for saving]
even what would be good, is have a setting that saved settings if you moved to another window. say im on the .sprites setting, but then click on a .lua file. the .sprites file has saved automatically from clicking on the other file. that would be nice, it wouldnt kill the flow

**Comment by suchipi** [comment]
It might also be nice to have File -> Save Project which saves all modified files in the current project.

**Comment by ivansafrin** [comment]
this is fixed in latest master
