### ISSUE TITLE
Can't run project saved on non-C: drive

### ISSUE THREAD

**Issue by SkyTheCoder** [ivansafrin/Polycode#601]
I have two drives built in to my computer, an SSD and an HDD (for faster startup, the SSD is my C: and the HDD is my E:). I store all my documents on my HDD, and I found that when attempting to run a project that was stored on my HDD (E:, not C:) it gave me errors on the default 3D project, redirecting me to Main.lua, saying that at line 0 a file could not be found, and giving me a blank screen in the Polycode player. The console says this:

Building project: template
Remote debugger client connected...
Error in file  on line 0
\Program Files (x86)\Polycode\Standalone\Player\lua\.lua'
	no file 'C
Backtrace:
In file  on line 0
File not available.
Remote debugger client disconnected...

It worked when I moved it over to my C: drive, but anyways, it's a bug, and I thought I should report it.

**Comment by suchipi** [comment]
I reported it here:
https://github.com/ivansafrin/Polycode/issues/591

But either way, yes, this bug is still present.
