### ISSUE TITLE
IDE Editor uses Roboto font

### ISSUE THREAD

**Issue by suchipi** [ivansafrin/Polycode#610]
The IDE's *.lua script editor is now using the Roboto (non-fullwidth) font.

![Sample image of editor using Roboto font](http://i.imgur.com/pOUnhlo.png)

**Comment by fodinabor** [comment]
Unconfirmed.. check the UIThemes' theme.xml https://github.com/ivansafrin/Polycode/blob/master/IDE/Contents/Resources/UIThemes/dark/theme.xml#L18
shouldn't have changed..

**Comment by suchipi** [comment]
The fonts there are "sans" and "mono" as they should be. The tree on the left is also using Mono, though I don't remember if it should or shouldn't.

**Comment by suchipi** [comment]
I re-ran the IDE directly from the Release folder and the fonts are loading correctly, so I must have copied it out to the folder where I keep my binary incorrectly. It's not entirely obvious to me what does and doesn't need to be copied; it'd be nice if that step was done automatically. Either way, this was my bad. Sorry!

**Comment by suchipi** [comment]
I realized that I was missing `default.pak` and `hdr.pak`. D'oh!
