### ISSUE TITLE
 Download hash mismatch when building dependancies - Linux

### ISSUE THREAD

**Issue by medchedli** [ivansafrin/Polycode#614]
Working on buiding the latest Polycode version from Github, I get a the following error output when  running "make" command : 

[  1%] Performing download step (download, verify and extract) for 'assimp'
-- downloading...
     src='http://download.sourceforge.net/assimp/assimp--2.0.863-sdk.zip'
     dst='/home/wassim/Polycode/Dependencies/Downloads/assimp--2.0.863-sdk.zip'
     timeout='none'
-- [download 0% complete]
CMake Error at assimp-stamp/download-assimp.cmake:9 (file):
  file DOWNLOAD HASH mismatch

```
for file: [/home/wassim/Polycode/Dependencies/Downloads/assimp--2.0.863-sdk.zip]
  expected hash: [9f41662501bd9d9533c4cf03b7c25d5b]
    actual hash: [d41d8cd98f00b204e9800998ecf8427e]
```

make[2]: **\* [assimp/src/assimp-stamp/assimp-download] Error 1
make[1]: **\* [CMakeFiles/assimp.dir/all] Error 2
make: **\* [all] Error 2

**Comment by marcopompili** [comment]
+1
