### ISSUE TITLE
[polycode c++] setColor does not work right

### ISSUE THREAD

**Issue by lewislepton** [ivansafrin/Polycode#621]
this has cropped up. but when using setColor like this:

    circle01 = new ScenePrimitive(ScenePrimitive::TYPE_CIRCLE,100,100,30);
    circle01->setColor(0.0, 1.0, 1.0, 1.0);
    circle01->setPosition(0);
    scene->addChild(circle01);
    
    circle02 = new ScenePrimitive(ScenePrimitive::TYPE_CIRCLE,50,50,30);
    circle02->setColor(1.0, 0.0, 1.0, 1.0);
    circle02->setPosition(0);
    circle01->addChild(circle02);
    
    circle03 = new ScenePrimitive(ScenePrimitive::TYPE_CIRCLE,30,30,30);
    circle03->setColor(0.0, 1.0, 0.0, 1.0);
    circle03->setPosition(0);
    circle02->addChild(circle03);

it does not make it green on the circle03. very strange. it seems fine for the first 2, but the third just doesn't go may other colors

**Comment by fodinabor** [comment]
adding something as a child with the parent having a color affects the child's color: there's a entity flag called colorAffectsChildren which you have to set to false to get the real colors (for the first 2 circles)

**Comment by lewislepton** [comment]
makes sense i guess. i just would have thought to make it less confusing that setColor would be univerasl in use.
why would it beike this though, i do know why as such, but wouldnt setColor be more efficient code wise?

cheers
