### ISSUE TITLE
Windows 64-bit binary for Polycode 0.8.4 crashes on Windows 8.1 Pro

### ISSUE THREAD

**Issue by vddev** [ivansafrin/Polycode#630]
"Polycode.exe has stopped working"

In the Windows application logs the following application error shows up:

"Faulting application name: Polycode.exe, version: 0.0.0.0, time stamp: 0x55677d8f
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00000000
Faulting process id: 0x3ec
Faulting application start time: 0x01d09a0f65f979d7
Faulting application path: *PATH*\PolycodeWin64_0.8.4\PolycodeDist\IDE\Polycode.exe
Faulting module path: unknown
Report Id: a3b70f9e-0602-11e5-8273-448a5bd17697
Faulting package full name: 
Faulting package-relative application ID: "

Also the next information event:

"Fault bucket 81872145200, type 5
Event Name: BEX
Response: Not available
Cab Id: 0

Problem signature:
P1: Polycode.exe
P2: 0.0.0.0
P3: 55677d8f
P4: StackHash_5861
P5: 0.0.0.0
P6: 00000000
P7: PCH_6C_FROM_ntdll+0x0003CA2C
P8: c0000005
P9: 00000008
P10: 

Attached files:
C:\Users\USER\AppData\Local\Temp\WERA344.tmp.WERInternalMetadata.xml

These files may be available here:
C:\Users\USER\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_Polycode.exe_211c32f488f88726188d94da7a4d168ec7a77b9_829027af_3421bfd5

Analysis symbol: 
Rechecking for solution: 0
Report Id: a3b70f9e-0602-11e5-8273-448a5bd17697
Report Status: 0
Hashed bucket: f5da444e4c6a4381933a2917a5e7f79d"

**Comment by ivansafrin** [comment]
It was actually built on Windows 8.1. What kind of video card do you have?

**Comment by vddev** [comment]
Ah, snap I could have thought about that. I keep forgetting I'm actually not working locally. I'm actually using remote desktop to my machine so it uses the RDP display driver, which must cause the issue.  The system has a AMD HD7890.

**Comment by fodinabor** [comment]
Jep - Polycode needs an OpenGL enabled device as rendering one (which is not what an RDP supports I guess ;-))..
