### ISSUE TITLE
Examples crash in Win7, 64 bit

### ISSUE THREAD

**Issue by JWki** [ivansafrin/Polycode#634]
All examples crash for me, both when building Polycode from source as well as when using the new binary release for Win64, I'm getting a "Failed to find program entry point 'GetPointerType' in 'User32.dll'" error at startup.
I've tried building Polycode from Source as a Win64 project, same error.
I've not tried yet to create a test project on my own and link Polycode to that.

**Comment by JWki** [comment]
Oh I should add, I'm compiling with Visual Studio 2013.

**Comment by ivansafrin** [comment]
Ahh, yes, I'm assuming you are on Windows 7. This is because of Windows 8 only stuff that's optional but made it into the build. I'll make new builds with it commented out.

**Comment by ivansafrin** [comment]
Ok should be fixed now both on github and in the binary release. Let me know if it works for you.

**Comment by JWki** [comment]
Well compiling the examples fails now, getting about a dozen linking errors. Unresolved external symbols, mostly constructors of Polycode classes (String, Vector3...).
I'd think the linker paths are messed up somehow, but if Polycore.lib wouldn't be found I suppose VS would complain about that first so I'm a bit puzzled.

**Comment by JWki** [comment]
So, compiling from source with the updated source code WORKS, none of the issues described above arise, HOWEVER, the Bullet dependencies fail to compile because some file names are too long, the compiler complains that it cannot write lines into these files.
As a result, the 3D physics examples do NOT compile because Polycode's 3D physics headers are missing, even though compiling the Polycode library itself doesn't show any errors, despite the fact that some dependencies just can't be there.

**Comment by ivansafrin** [comment]
The template is set to Win32 by default and it's a 64-bit build of Polycode, so you have to manually set the template to Win32.

As far as the path being too long, that's a VS problem. Not much I can do about that.

**Comment by ivansafrin** [comment]
I'll close this issue as the original was resolved.
