### ISSUE TITLE
Open in external editor not working on OS X 10.10

### ISSUE THREAD

**Issue by CandyFace** [ivansafrin/Polycode#636]
After toggling "use external editor" and selecting my preferred editor (Sublime Text), clicking on a lua script does not open the editor. I have to manually find the files and open them.

If this is a bug, then i may be able to fix it myself, though it if it something that has to be implemented, then i'll probably have to wait till someone does it as my c/c++ knowledge is quite barebone.

**Comment by ivansafrin** [comment]
Should be fixed in latest master.
