### ISSUE TITLE
[0.8.4] [C++] Crash when creating a Polycode::Scene

### ISSUE THREAD

**Issue by DaZombieKiller** [ivansafrin/Polycode#655]
In my project I have a class called "Engine" that is instantiated at program startup, its constructor looks like this:

    Engine::Engine(HINSTANCE hInstance, int nCmdShow, LPCTSTR windowTitle, bool resizable, bool showDebugConsole)
    {
    	view = new Polycode::PolycodeView(hInstance, nCmdShow, windowTitle, resizable, showDebugConsole);
    	sceneHud = new Polycode::Scene(Polycode::Scene::SCENE_2D_TOPLEFT);
    	scene2d = new Polycode::Scene(Polycode::Scene::SCENE_2D);
    	scene3d = new Polycode::Scene(Polycode::Scene::SCENE_3D);
    	isRunning = true;
    	printf("Engine init\n");
    }

However, each of the three lines creating instances of Polycode::Scene will cause an instant crash.
I'm completely stumped as to why this would happen.
I'm using Visual Studio 2013 Express, if that is relevant.

**Comment by ivansafrin** [comment]
You need to create the core before doing anything else.

**Comment by DaZombieKiller** [comment]
Heh, I thought you were pulling my leg for a second there, since I could've sworn that I had initialized the core, but it seems I must've accidentally removed that code while reorganizing my project. Thanks!
