### ISSUE TITLE
png_sizeof() is deprecated; avoid its use

### ISSUE THREAD

**Issue by Keyaku** [ivansafrin/Polycode#662]
According to the change for libpng version 1.6.0beta27 (August 11, 2012), `png_sizeof()` is deprecated.  
Changing to `sizeof()` will certainly support versions ALL versions, including the 1.5.10 that is downloaded in Dependencies/, since it's simply a `#define png_sizeof(x) (sizeof (x))`, according to pngconf.h.

What are your thoughts?

**Comment by ivansafrin** [comment]
The "goodbye_cmake" branch, which is on its way to becoming the new master dropped libpng in favor of more compact and portable png reading code.

**Comment by Keyaku** [comment]
Oh, all right. Sorry, should've looked into it.
