### ISSUE TITLE
Editor stuck in "ctrl down mode" when running project using CTRL-R

### ISSUE THREAD

**Issue by Prime8bit** [ivansafrin/Polycode#671]
I am using Polycode IDE on windows and when I run my project using CTRL-R then after I close the game I find I cannot edit the script I working on any more. This is due to the fact that Polycode IDE believes I am still pressing CTRL. If I hit 'A' then it selects all, if I hit 'R' it runs again. This mode can only be canceled by pressing and releasing CTRL.

Edit 1: A related issue occurs when you use an external text editor. If you use an external editor and click on a script for editing, it opens just fine. As soon as you go back to Polycode IDE it is in "ALT down mode" and you mush press and release ALT to get out of this mode.

**Comment by fodinabor** [comment]
well there's already a fix for this: #606
But it won't be merged in master for quiet some time as there's another branch that will need manual merges..
