### ISSUE TITLE
[Idea] Polycode feature Plug in system

### ISSUE THREAD

**Issue by carlosmarti** [ivansafrin/Polycode#679]
Somethings that i see polycode could have to possibly make it a bit better.

Having a plug in system for example something like Superpowers game engine or Minko3d Framework.
This will allow to add only what is needed for your project and not bloat the project with stuff you're not even using. 

Also making it user friendly for people that want to make there own plug ins to add there own physics engine for instance can do so without much hassle. I think Minko3d does this well some pointers could be taken from them.

**Comment by ivansafrin** [comment]
Please don't post feature requests as issues. If you would like to discuss this, post on the polycode site forum.
