### ISSUE TITLE
Mistyping in Goodbye Cmake branch [win32, msvc, build failed]

### ISSUE THREAD

**Issue by bagobor** [ivansafrin/Polycode#680]
PolyOpenGLGraphicsInterface.h, line 44

WINAPI_FAMILIY_PHONE_APP
should be 
WINAPI_FAMILY_PHONE_APP

**Comment by bagobor** [comment]
And can you please update visual studio files to latest visual studio community (vs2015). As it's free for personal use or small teams.

**Comment by fodinabor** [comment]
Whoops.. Merge issue..

And nope I don't think offering only 2015 files is right, as there are far too many use cases in which you may not use Community .. And you still can open 2013 files with 2015 and also you can easily upgrade .. 
Only issue here is that the libs are 2013 - i know.. Maybe we should offer both or just a directory with links to the source of the deps...

**Comment by ivansafrin** [comment]
Yeah, I'm not sure on this myself. I use 2015 and upgraded the project files in my local repo but have been hesitant to commit. It's nice having 2013 compatibility, but 2015 is free and looks like the future, so I'm leaning towards upgrading the repo to 2015. The problem with people manually upgrading their local projects to 2015 is you have to manually set the runtime to 2013 (2015 runtime gutted a lot of standard library stuff and there are tons of errors that I do not feel like dealing with). The existing libs work fine with that.

**Comment by ivansafrin** [comment]
I committed the typo fix. Gonna think on the 2015 thing, but so far leaning towards a yes.
