### ISSUE TITLE
Cannot build on Linux

### ISSUE THREAD

**Issue by ghost** [ivansafrin/Polycode#683]
-- Installing: /home/donvlad/Development/Polycode/Standalone/../Release/Linux/Standalone/Docs/html/js/bootstrap.js
CMake Error at cmake_install.cmake:48 (FILE):
  file INSTALL cannot find
  "/home/donvlad/Development/Polycode/Standalone/../Release/Linux/Framework/Player/PolycodePlayer".

make: **\* [install] Error 1

**Comment by fodinabor** [comment]
There seems to be an error before - have a look whether you find anything else.

**Comment by ghost** [comment]
The only things I get before what I posted is "--Installing:" so everything that's error is in what I posted

**Comment by fodinabor** [comment]
I know the log is very verbose.. maybe forward the output to a logfile (BuildLinux.sh > log.txt) and then search for error in this file.. 

Why I think there has to be an error before? The error message states that the PolycodePlayer file cannot be found - it should have been built earlier - so if there was an error before it would be quiet obvious that the file PolycodePlayer does not exist..

**Comment by ghost** [comment]
I switched to the latest branch hoping I can compile on Linux but I get this error.

Linking [Studio/Polycode]
/usr/bin/ld: skipping incompatible ../../lib/linux/libfreetype.a when searching for -lfreetype
/usr/bin/ld: cannot find -lfreetype
/usr/bin/ld: skipping incompatible ../../lib/linux/libphysfs.a when searching for -lphysfs
/usr/bin/ld: cannot find -lphysfs
/usr/bin/ld: skipping incompatible ../../lib/linux/libportaudio.a when searching for -lportaudio
/usr/bin/ld: cannot find -lportaudio
/usr/bin/ld: skipping incompatible ../../lib/linux/libz.a when searching for -lz
/usr/bin/ld: skipping incompatible ../../lib/linux/libGLEW.a when searching for -lGLEW
/usr/bin/ld: skipping incompatible ../../lib/linux/liblua.a when searching for -llua
/usr/bin/ld: cannot find -llua
collect2: error: ld returned 1 exit status
Makefile:115: recipe for target 'studio' failed
make: *** [studio] Error 1

Is there a stable source code somewhere that contains the latest branch that I can compile?
