### ISSUE TITLE
[OSX] Building from terminal from folder doesn't work

### ISSUE THREAD

**Issue by MrStevns** [ivansafrin/Polycode#684]
Hi

I am currently working on a sublime addon that will make it possible for me to compile polycode applications directly from the Sublime Text IDE. I've noticed though that when you compile from terminal, and are located in a deeper layer from where the .polyproject is, then polybuild won't copy folders or their content, and will instead just spit out a 1kb file, with a xx.polyapp and DemoApp.polyapp (both 0 byte) within the compiled .polyapp

For example if we say i'm located in the Game/Scripts folder run this: 
`polybuild --config=../Game.polyproject --out=../Game.polyapp`
then I would expect it to look back into the parent folder, and wrap up everything nicely, However while it locates the polyproject file and compiles successfully, it doesn't copy the folders.

If i'm located in /Game/ (the parent folder) and run:
`polybuild --config=Game.polyproject --out=Game.polyapp`
then it works. 

This is a bug right, or have I misunderstood something?

**Comment by fodinabor** [comment]
Hey,
when the IDE starts applications like polybuild, polyimport or anything else it uses a parameter to say in which folder to work. So the command to be executed looks like `cd "workFolder" && applicationToExecute --param` (see [CocoaCore](https://github.com/ivansafrin/Polycode/blob/37a40fefe194ec7f6e9d1257f3bb3517b0a168bc/Core/Contents/Source/PolyCocoaCore.mm#L306))
I guess it would be a nice addition if it would search for the right directory by itself - but it is not necessary when used integrated in Polycode ... maybe the command `cd .. && ..` structure helps you, too?

**Comment by MrStevns** [comment]
Ahh okay, yeah I thought it would have to be something like this. Bah.. then i'll have to resort to some shell script for this to work properly with Sublime -.-'

Thanks anyway fodinabor ;)
