### ISSUE TITLE
Mesh::getRadius() Always returns Zero

### ISSUE THREAD

**Issue by factorydefault** [ivansafrin/Polycode#701]
Changes to Mesh::getRadius() within a9b5d1ece3615d583a6bfd70b0ea55b288b1e3e9 cause a repeated comparison of the length of an unassigned Vector3 vec:

https://github.com/ivansafrin/Polycode/blob/37a40fefe194ec7f6e9d1257f3bb3517b0a168bc/Core/Contents/Source/PolyMesh.cpp#L92-L103

**Comment by fodinabor** [comment]
is fixed in goodbye_cmake
