### ISSUE TITLE
Problem compiling for windows

### ISSUE THREAD

**Issue by Drakaroft** [ivansafrin/Polycode#707]
Hi, i want to try to compile the engine+editor, initially i think i need to open and build the .sln in Win32 but i get very strange error, what i'm doing wrong?

**Comment by fodinabor** [comment]
would be nice to see the output of the error.

**Comment by Drakaroft** [comment]
Yeah, Thanks!! The error are:
1)"error C1083: Cannot open include file: 'polycode/core/PolyCoreServices.h': No such file or directory C:\download browser\polycode-goodbye_cmake\src\modules\physics3d\polyphysicsscene.cpp   31"

2)"error LNK1104: cannot open file 'portaudio.lib'"

3)"error C2653: 'CoreServices' : is not a class or namespace name    c:\download browser\polycode-goodbye_cmake\build\windows\win32\polycodestudio\main.cpp 91"

4)"error C2227: left of '->getDefaultWorkingDirectory' must point to class/struct/union/generic type    C:\download browser\polycode-goodbye_cmake\build\windows\win32\polycodestudio\main.cpp 91"

5)"error C2227: left of '->getCore' must point to class/struct/union/generic type   C:\download browser\polycode-goodbye_cmake\build\windows\win32\polycodestudio\main.cpp 91"

6)"IntelliSense: name followed by '::' must be a class or namespace name    C:\download Browser\Polycode-goodbye_cmake\build\windows\win32\PolycodeStudio\main.cpp  91"

7)"error C2660: 'registerFileType' : function does not take 3 arguments f:\mysystem2\download browser\polycode-goodbye_cmake\build\windows\win32\polycodestudio\main.cpp    91"

8)"error C3861: 'getInstance': identifier not found C:\download browser\polycode-goodbye_cmake\build\windows\win32\polycodestudio\main.cpp 91"

**Comment by fodinabor** [comment]
well - first one: remove line 31 from `C:\download browser\polycode-goodbye_cmake\src\modules\physics3d\polyphysicsscene.cpp`
second: do you have downloaded the submodule with the library files?
if you use this as `C:\download browser\polycode-goodbye_cmake\build\windows\win32\polycodestudio\main.cpp` this should fix the rest: https://gist.github.com/fodinabor/ffb9f675ea762cef0b6484a203e658e0

**Comment by Drakaroft** [comment]
Where can i download the submodule with the library files? I have downloaded only the "goodbye_cmake" repository D:

**Comment by fodinabor** [comment]
Did you download it via git or did you use the zip download function? With git you'd have to make git submodule --init in the repository - with zip you may download https://github.com/ivansafrin/PolycodeDepBinaries as well and extract it to the lib folder in your current installation.

**Comment by Drakaroft** [comment]
Hi sorry for the delay, i see on the forum that all person get Polycode using git, while i download it from the repo, what i need to write in Git for download Polycode?

I'm sorry for my english i'm studying to improve it.

**Comment by fodinabor** [comment]
```
git clone git@github.com:ivansafrin/Polycode.git  
git checkout origin/goodbye_cmake  
git submodule update --init "lib"
```
