### ISSUE TITLE
Why isn't C++ a centered language?

### ISSUE THREAD

**Issue by Raj2032** [ivansafrin/Polycode#715]
C++ is a great language. It is very powerful, it is more low level language, which means that people have a lot more explicit control over what they do, and performance is far better. I am looking forward to use Polycode, especially when the new rewrite version is going to be released.

The problem I have currently with Polycode is that C++ is NOT a centered language, like it is in Unreal engine. Why don't we make it a well centered language as well as to have proper tutorials as well?

**Comment by Raj2032** [comment]
Seems like a great idea. So far I have not been able to find a game engine that is C++ focused. It would be great to see something like this to be implemented.

**Comment by Joe23232** [comment]
Seems like a great idea. So far I have not been able to find a game engine that is C++ focused. It would be great to see something like this to be implemented.

**Comment by Raj2032** [comment]
Hi Ivansafrin, may I know why did you close this issue?

**Comment by ivansafrin** [comment]
Polycode is written almost entirely in C++, I do not understand the question.

**Comment by Raj2032** [comment]
Yes I understand that but when it comes to developing games using Polycode,
you mentioned that in order to use C++ we need to use a native library,
which means that C++ is NOT a centered langauge. What I am trying to ask is
to make C++ a centered, main language when using the game engine to make
games, like Unreal Engine.

**Comment by ivansafrin** [comment]
The Polycode rewrite will be distributed solely as a native library. I don't understand what you mean by "centered language". The Polycode rewrite doesn't have an IDE and consists ONLY of a native library. How you use it is up to you.

**Comment by Raj2032** [comment]
As I am still an unexperienced programming who lacks knowledge on how all
of this stuff works, this what what the other guy said about the issue we
both wish to be resolved (he tweeted this on Twitter)

"I'm asking in the name of a few users that are looking for the past months
for a game engine straigthtforward, documented, and above all C++ centered:
is C++ supported as a main, built-in scripting language for game logic (see
Unreal)? NOT for native libraries and NOT bindings."

**Comment by ivansafrin** [comment]
Please, familiarize yourself with the project before opening issues. Thanks.

**Comment by Raj2032** [comment]
But what about what the other dude said? Isn't it possible for the team to
follow up on the other guy's request?

**Comment by Biacode** [comment]
I think when you want to write a game in pure C++ then you should be able to deal with setting up and understanding core of the engine. For instance, it should not be that hard to compile the engine from source codes and use them from your own project.

**Comment by Raj2032** [comment]
Ok tell me this, are you able to AT LEAST attach C++ scripts onto
individual objects just like in Unity (a game engine) where the user can
attach a C# script to an object?
